### ISSUE TITLE
Custom Colors Possible?

### ISSUE THREAD

**Issue by alecksjaycubd** [dlamon1/clockotron#1]
Just wondering if custom timer colors would be possible. Or the ability for COT not to change the color of the title at all?

**Comment by dlamon1** [comment]
I can add custom colors, sure. It will be a few weeks. To have the color not change, change the color of the trigger to the same color as the count down or count up color.

**Comment by dlamon1** [comment]
I misunderstood. Hmm, currently no, there is no way to turn the color change off. I will look at this

**Comment by alecksjaycubd** [comment]
Thanks. I just need a different color than you offer. Not all my timers are typical countdowns. Sometimes I have to match logo colors for a countdown to the start of the show for instance. I know nothing about programming so if it’s easier, just being able to turn the up and down color off would work, too. 
So far I it’s a super helpful little app. For the video timer I don’t know how you were able to make it work even if a video is on a layer. I’ve had a bunch of different things in the past but none of them could figure that out!

Alex

**Comment by dlamon1** [comment]
Custom colors are now available in v1.0.1 in the Settings Tab. Happy to hear the video timer feature is working out for you.
